### PR TITLE
[deps] Upgrade all deps

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
Upgrades all dependencies to latest, adds a comment around the failing installation on Mac due to sqllite

### Checklist

- Do all Lints pass?
  - [x] Have you ran `pnpm spellcheck`?
  - [x] Have you ran `pnpm fmt`?
  - [x] Have you ran `pnpm lint`?

### CODE REVIEW

**Review by hariria — COMMENTED** [review]
Did you try building each to make sure they don't break? I think upgrading some of these deps breaks the apps / packages / workers. i.e., code-cache expects `itty-router` v2.

**Comment by gregnazario** [comment]
> Did you try building each to make sure they don't break? I think upgrading some of these deps breaks the apps / packages / workers. i.e., code-cache expects `itty-router` v2.

Do we not build them all in CI?

**Comment by hariria** [comment]
No CI doesn't build anything

**Comment by gregnazario** [comment]
> No CI doesn't build anything. The Vercel / Netlify deployments do but they don't build the `workers` code because there's no dependency there

Well then we should add it so it builds these pieces, otherwise, we won't know if they break outside of manual testing

**Comment by hariria** [comment]
Sure that's a good idea and I can do that after, but I don't think its a good idea to willy-nilly upgrade all the dependencies in the repo. Even if it compiles, they may not work as expected when run. Probably should be more surgical

**Comment by gregnazario** [comment]
> Sure that's a good idea and I can do that after, but I don't think its a good idea to willy-nilly upgrade all the dependencies in the repo. Even if it compiles, they may not work as expected when run. Probably should be more surgical

Fine by me.  I'll cancel out these changes, but we need to separate this worker build from everything else, and add a real CI system for it.

**Pull request closed without merging**
