### PR TITLE
Populate Tailwind Config

### PR DESCRIPTION
**Pull request by blakezimmerman**
### Description

This PR populates the Tailwind config with our theme for the new docs site. It also stubs out a React component to serve as the entry point for the landing page (and to ensure that the Tailwind theme works).

The largest piece of work in this PR, however, is the custom Tailwind plugin I wrote to handle our theme colors. Its API was heavily influenced by my time spent using PandaCSS.

#### Custom Plugin Details

I'm not a fan of how Tailwind expects you to handle light/dark mode. They generally expect something like:

```jsx
className="bg-zinc-50 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-50"
```

With this syntax, implementing light/dark mode is a very conscious effort and if there's any non-trivial changes to your site's colors, it might take a while to update all of your components.

I'd much rather define my styles like this:

```jsx
className="bg-background-primary text-text-primary"
```

In this style, the class names simply describe their purpose and the concept of light/dark mode is abstracted away. In your Tailwind theme, you should be able to specify the light and dark colors for these tokens.

Unfortunately, this is not possible out of the box with Tailwind. To work around it, I wrote a plugin that allows you to define your color palettes and a set of semantic colors that can specify separate values for both light and dark mode. Under the hood, these semantic colors are represented as CSS variables that automatically update their value when a `dark` class is present in the document. The plugin automatically handles generating the CSS variables for you.

One additional note is that all of the colors are specified using the `oklch` format so that we can support more rich colors for those with high-end displays. A PostCSS plugin is then applied to the output so that fallback `rgba` values are present for those using browsers that don't support the modern `oklch` format.

Below is an example of how you can define your colors with this plugin:
```js
const { themeColors, colorsPlugin } = createOklchColors((oklch) => ({
  colors: {
    white: oklch(100, 0, 0),
    black: oklch(0, 0, 0),
    red: {
      200: oklch(84, 0.02, 30),
      500: oklch(84, 0.08, 30),
      800: oklch(72, 0.15, 30),
      900: oklch(40, 0.1, 30),
    },
  },
  semanticColors: {
    background: {
      DEFAULT: { base: "white", dark: "black" },
      secondary: { base: oklch(22, 0.03, 216) },
      danger: { base: "red-500", dark: "red-800" },
    },
    text: {
      primary: { base: "black", dark: "white" },
    },
    border: { base: "black/50", dark: "white/50" },
  },
}));
```

### Checklist

- Do all Lints pass?
  - [] Have you ran `pnpm spellcheck`?
  - [] Have you ran `pnpm fmt`?
  - [] Have you ran `pnpm lint`?

### CODE REVIEW

**Comment by hariria** [comment]
Hey blake thanks for the work here! Is there any chance we could make the custom tailwind styling only apply to the landing page? I think we wanted to keep the styling of the rest of the docs as is.

**Comment by blakezimmerman** [comment]
> Hey blake thanks for the work here! Is there any chance we could make the custom tailwind styling only apply to the landing page? I think we wanted to keep the styling of the rest of the docs as is.

The styling of all the other pages appears to be unaffected. Looks like Nextra prefixes all of their Tailwind classes with a `_` to prevent any collisions with the user-land Tailwind config.

**Comment by hariria** [comment]
I'm not sure that's true. The font-family has changed for the rest of the docs site and the cards look very different for example (https://developer-docs-nextra-git-bz-tailwind-config-aptoslabs.vercel.app/en/docs)

**Comment by blakezimmerman** [comment]
> I'm not sure that's true. The font-family has changed for the rest of the docs site and the cards look very different for example (https://developer-docs-nextra-git-bz-tailwind-config-aptoslabs.vercel.app/en/docs)

Ah okay, I see what's going on now. So all the components direct from Nextra are unaffected, but all of the components we defined in the `components` folder are affected. Additionally, the font is being applied globally. I'll continue to hack away at this branch and see what I can do. Sorry for the misunderstanding.

**Comment by hariria** [comment]
It's not just the components defined in `components`. It's other ones as well. [Filetree](https://developer-docs-nextra-git-bz-tailwind-config-aptoslabs.vercel.app/en/docs/components/filetree) looks different and is from `nextra/component`, the `kbd` in the searchbar, which is also defined in `nextra`, is also affected, a lot of the borders have changed as well.

**Comment by moonclavedev** [comment]
@hariria @blakezimmerman is the intention for the new docs site to remain as default Nextra styles? If that's the case I wonder what's the point of styling the docs homepage differently. 

Was there custom work from the design team for the new docs site in it's entirety?

**Comment by hariria** [comment]
Let me dm you :)

**Comment by blakezimmerman** [comment]
> Appreciate it, thanks. By the way, it's not just the components defined in `components`. It's other ones as well. [Filetree](https://developer-docs-nextra-git-bz-tailwind-config-aptoslabs.vercel.app/en/docs/components/filetree) looks different and is from `nextra/component`, the `kbd` in the searchbar, which is also defined in `nextra`, is also affected, a lot of the borders have changed as well. Mermaid font family is also different now.

Good catch, looks like there's a low-specificity rule for coloring that border and it's being overridden somewhere. I'll have to a deep dive today to sort all of this out.
Screenshot 2024-04-11 at 2 41 08 PM

**Review by hariria — CHANGES_REQUESTED** [review]
Nice job! A couple things

1. Navbar color distortion

```css
:root :has(.landing-page) {
    background-color: var(--background-primary);
}
```

is influencing the color of the header on the landing page. When I remove it, it looks normal. Here's the color distortion I'm talking about:

Screenshot 2024-04-11 at 3 31 11 PM


2. dark mode / i18n selection footer is missing

Any chance we could add back the dark mode selector + i18n selector at the bottom of the landing page?

**Comment by blakezimmerman** [comment]
> Nice job! A couple things
> 
> 1. Navbar color distortion
> 
> ```css
> :root :has(.landing-page) {
>     background-color: var(--background-primary);
> }
> ```
> 
> is influencing the color of the header on the landing page. When I remove it, it looks normal. Here's the color distortion I'm talking about:
> 
> Screenshot 2024-04-11 at 3 31 11 PM
> 2. dark mode / i18n selection footer is missing
> 
> Any chance we could add back the dark mode selector + i18n selector at the bottom of the landing page?

1. So the reason for this is because you currently have the site in light mode. The nav bar has some translucency so the dark mode background behind it makes it look weird. If you switch the site to dark mode, it'll look good. Even if I remove the background on the document, you still get the same issue as soon as you scroll. Unfortunately I can't force dark mode for just this page, however, this will be a non-issue as soon as we get the landing page light theme from Chelsea.
2. My plan was to work the theme selector and i18n selector into landing page design once I start building the page out, but I can include the default Nextra one in the meantime if you want.

**Review by hariria — APPROVED** [review]
gracias señor

**Pull request merged**
