### PR TITLE
add Pyth to Aptos

### PR DESCRIPTION
**Pull request by mariobern**
### Description

Hi all, Mario from Pyth here. Would like to add Pyth oracle and how to use Pyth on Aptos for developers 

### Checklist

- Do all Lints pass?
  - [x] Have you ran `pnpm spellcheck`?
  - [x] Have you ran `pnpm fmt`?
  - [x] Have you ran `pnpm lint`?

### CODE REVIEW

**Review by gregnazario — COMMENTED** [review]
@igor-p what you think about adding oracles here?

**Review by hariria — COMMENTED** [review]
I think it might be good to have `Oracles` be its own directory, and have `pyth` as a subfile inside that

**Comment by igor-p** [comment]
> I think it might be good to have `Oracles` be its own directory, and have `pyth` as a subfile inside that

I agree. Adding another oracle in this single page layout would make it unwieldy. The main `Oracles` page could have the blurb about what oracles are, then maybe link to the sub-page on the page itself (in addition to the sidebar)?

**Comment by mariobern** [comment]
hi all @igor-p @gregnazario @hariria let me know if there's anything I can do to expedite this!

Want to make sure that the Aptos community can leverage Pyth oracles when building their projects

**Review by hariria — APPROVED** [review]
@igor-p i think we can merge and then move around after Wdy think

**Pull request merged**
