### PR TITLE
Update the Move Object pages

### PR DESCRIPTION
**Pull request by jmintuitive**
### Description

Updates the Move Object pages in the Advanced Move section.

### Checklist

Incorporates all feedback from reviewers on the content. All links have been checked.

- Do all Lints pass?
  - [ ] Have you ran `pnpm spellcheck`?
  - [X] Have you ran `pnpm fmt`?
  - [X] Have you ran `pnpm lint`?

### CODE REVIEW

**Comment by jmintuitive** [comment]
@gregnazario @hariria This is ready for review :)

**Review by hariria — COMMENTED** [review]
Could we move this under Standards? And remove the duplication?

**Comment by jmintuitive** [comment]
@hariria I updated it with the last bit of context missing from the Standard page, then used this updated version to replace the standard. (So it is NOT in the advanced guide anymore, and all the relative links have been updated :) )

**Review by hariria — APPROVED** [review]

**Comment by hariria** [comment]
@jmintuitive branch has some conflicts but lgtm

**Pull request merged**
