### PR TITLE
Add Chinese translations, including the API and the Getting Started section.

### PR DESCRIPTION
**Pull request by WGB5445**
### Checklist

- Do all Lints pass?
  - [ ] Have you ran `pnpm spellcheck`?
  - [x] Have you ran `pnpm fmt`?
  - [x] Have you ran `pnpm lint`?

### CODE REVIEW

**Review by hariria — COMMENTED** [review]
@WGB5445 can you rebase on latest?

**Review by hariria — COMMENTED** [review]
Seems like there's no page here: https://developer-docs-nextra-git-cn-translation-aptoslabs.vercel.app/zh/build/apis?

**Comment by igor-p** [comment]
Yeah I'm seeing the `Indexer GraphQL API` page missing (https://developer-docs-nextra-i0gqpwdy2-aptoslabs.vercel.app/zh/build/indexer) and the navigation at the bottom of the page seems to skip over it.

**Comment by igor-p** [comment]
Ok actually I'm seeing that in the `en` docs, navigating to `APIs` -> `Indexer GraphQL API` subpage redirects to the `Indexer` folder (basically skipping ahead). I think, instead of redirecting, there should be some short text about the Indexer (with a link to the Indexer api page). But in any case, separate issue from this PR.

@WGB5445 in the Chinese version, I think we can just remove the link to the indexer page from the sidebar.

https://github.com/user-attachments/assets/de09aef1-ce35-45b6-bf95-d9f92f232c81

**Comment by WGB5445** [comment]
> Ok actually I'm seeing that in the `en` docs, navigating to `APIs` -> `Indexer GraphQL API` subpage redirects to the `Indexer` folder (basically skipping ahead). I think, instead of redirecting, there should be some short text about the Indexer (with a link to the Indexer api page). But in any case, separate issue from this PR.
> 
> @WGB5445 in the Chinese version, I think we can just remove the link to the indexer page from the sidebar.
> 
>  missing.indexer.page.mov

yes, we shouldn’t keep a URL that is either unclickable or leads to errors, so I’ve set it to the English version: `en/build/indexer`.

**Review by igor-p — APPROVED** [review]

**Pull request merged**
