### PR TITLE
Address some compiler warnings and errors

### PR DESCRIPTION
**Pull request by Levi0804**
### Description

This PR addresses compiler errors and warnings by passing correct arguments into functions as per their signature and removing unused imports that were causing warnings

### Checklist

- Do all Lints pass?
  - [x] Have you ran `pnpm spellcheck`?
  - [x] Have you ran `pnpm fmt`?
  - [x] Have you ran `pnpm lint`?

### CODE REVIEW

**Review by JohnChangUK — APPROVED** [review]
Thanks for amending :)

**Comment by Levi0804** [comment]
> Thanks for amending :)

Happy to contribute, thanks for reviewing the changes :)

**Comment by Levi0804** [comment]
Hey there, I was wondering if there's anything in this pull request that might need tweaking. I'm happy to make any changes. Thanks for taking a look :D

**Review by gregnazario — APPROVED** [review]

**Comment by JohnChangUK** [comment]
> Hey there, I was wondering if there's anything in this pull request that might need tweaking. I'm happy to make any changes. Thanks for taking a look :D

Merged, thanks for the help <3

**Pull request merged**
